### ISSUE TITLE
Error en url hace que ambiente producto falle

### ISSUE THREAD

**Issue by johnowenatala** [TransbankDevelopers/transbank-sdk-ruby#57]
En esta línea:

https://github.com/TransbankDevelopers/transbank-sdk-ruby/blob/44ea5886b4f3dfefefdde160d29b1cf0f08be33f/lib/transbank/sdk/webpay/webpay_plus/deferred/deferred_transaction.rb#L10

la url parte con "/", lo que genera una url como esta: https://webpay3g.transbank.cl//rswebpaytransaction/api/webpay/v1.0/transactions/token... (doble slash tras el hostname).

Normalmente esto no generaría problemas, pero en producción esto hace que el servidor de Transbank corte la conexión, generando este error:

EOFError (end of file reached)
/home/usuario/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:225:in `rbuf_fill'
/home/usuario/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
/home/usuario/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
/home/usuario/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
/home/usuario/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
/home/usuario/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
/home/usuario/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
/home/usuario/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
/home/usuario/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1492:in `request'
/home/usuario/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1485:in `block in request'
/home/usuario/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:933:in `start'
/home/usuario/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1483:in `request'
/home/usuario/apps/my_app/shared/bundle/ruby/2.7.0/gems/transbank-sdk-1.4.0/lib/transbank/sdk/utils/net_helper.rb:36:in `http_put'
/home/usuario/apps/my_app/shared/bundle/ruby/2.7.0/gems/transbank-sdk-1.4.0/lib/transbank/sdk/webpay/webpay_plus/deferred/deferred_transaction.rb:89:in `capture'
(...)

**Comment by ffiebig** [comment]
Hubo una restructuración grande del SDK, esto ya no debería ocurrir
