### ISSUE TITLE
Obtener el tipo de tarjeta

### ISSUE THREAD

**Issue by abelorian** [TransbankDevelopers/transbank-sdk-ruby#59]
Existe alguna forma de saber si la tarjeta agregada en OneClick es débito o crédito? 

Por ahora el credit_card_type retorna RedCompra, Visa, Master, etc.. pero no hay un campo específico _payment_type_code_ así como cuando se hace un pago (authorize)

**Comment by ffiebig** [comment]
Card type es el único dato sobre que tarjeta es que devuelve el API.

No lo he probado, sin embargo, la respuesta de una tarjeta de Débito (aunque sea Visa o similar) creo que devuelve RedCompra de todas formas. Con eso deberías poder discernir si es Débito, Crédito o Pre-pago

Prepago tiene debería también tener su propio tipo
