### ISSUE TITLE
Invalid status '19' for transaction while authorizing. Commerce will be notified by webpay to authorize

### ISSUE THREAD

**Issue by matiasmenares** [TransbankDevelopers/transbank-sdk-ruby#67]
Me han llegado transacciones que dan el siguiente error al hacer commit

![image](https://user-images.githubusercontent.com/14056054/117088185-b4922480-ad1f-11eb-82cb-af8723a988c7.png)

"Invalid status '19' for transaction while authorizing. Commerce will be notified by webpay to authorize"

Después de hacer un status al token ( Transbank::Webpay::WebpayPlus::Transaction::status(token: token) )me dice response_code = 0 y vci = ABO (Autenticación abortada por tarjetahabiente)

A pesar que no dio authorization_code ni card_detail, en Transbank::Webpay::WebpayPlus::Transaction::commit suelta una excepción, esto me ha pasado un par de veces.

**Comment by mvarlic** [comment]
Es un error retornado por el api de Transbank
