### ISSUE TITLE
Error al hacer refund de una transaccion de mall

### ISSUE THREAD

**Issue by tomasmiguez** [TransbankDevelopers/transbank-sdk-ruby#73]
**Describe el bug**
Al intentar anular una transacción, falla  con un error en la gema.
 
**Para reproducir**

`require 'transbank/sdk'`
`tx = Transbank::Webpay::WebpayPlus::MallTransaction.new(::Transbank::Common::IntegrationCommerceCodes::WEBPAY_PLUS_MALL)`
`tx.refund('123456', '124553', '3242352rw', 1233)`

**Comportamiento observado**

Se obtiene la siguiente excepción:
![image](https://user-images.githubusercontent.com/53789223/168132801-979b3da7-7a72-4f78-9c3d-85a74bd8d23b.png)

**Versiones (por favor agrega aquí la siguiente información):**
- SDK: 2.0.0
- Ruby: 3.1.0
- Bundler: 2.3.4

**Contexto adicional**

El error parece surgir de que sobra un chequeo en el método `refund`, para un objeto que no existe:
![image](https://user-images.githubusercontent.com/53789223/168133307-014161c9-bdc1-4ab0-b3a4-edc787bd126f.png)
Eso es en:
https://github.com/TransbankDevelopers/transbank-sdk-ruby/blob/master/lib/transbank/sdk/webpay/webpay_plus/mall_transaction.rb#L51

**Comment by danirod** [comment]
Me encontré con el mismo bug. Esa variable ni siquiera se está intentando utilizar posteriormente dentro de la función. ¿Puede ser que toda esa línea de validación sobre completamente?

**Comment by rblancou** [comment]
@mvarlic @isabellaahc @ffiebig ¿Podrían valorar esta issue y la corrección levantada por @danirod por favor?

**Comment by isabellaahc** [comment]
Hola @rblancou, lamento la demora en la respuesta, estamos revisando. Les comentaremos cuando se solucione el bug reportado.

**Comment by isabellaahc** [comment]
@rblancou @danirod, se revisó el PR propuesto por @danirod y se confirmaron los cambios a Master.
Hoy realizaremos el release incluyendo esta mejora.
Una vez más, muchas gracias por el aporte 🎉

**Comment by isabellaahc** [comment]
Estimados, damos por cerrado este issue. Pueden encontrar la solución en el siguiente release del SDK: https://github.com/TransbankDevelopers/transbank-sdk-ruby/releases/tag/v2.0.1
